### ISSUE TITLE
ArcGIS API add_users method seems to only accept a max of 25 usernames

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/kartograafr#34]
When running the application with the updated dependencies, an error seems to be thrown when a large number of users are passed to the `group.add_users()` call. See [line 111](https://github.com/tl-its-umich-edu/kartograafr/blob/8d27d50e9a9bbbf74dcb1c7e059a6ce8e8d803f4/arcgisUM.py#L111).

```
RuntimeError: Exceeded maximum number of users allowed per call.
(Error Code: 400)
```

This seems to be caused by a limit imposed by the [ArcGIS REST API](https://developers.arcgis.com/rest/users-groups-and-items/add-users-to-group.htm).

**Comment by ssciolla** [comment]
You can see my progress on this issue [in this branch comparison](https://github.com/tl-its-umich-edu/kartograafr/compare/master...ssciolla:issue-34-handle-long-user-lists).

**Comment by lsloan** [comment]
Does this issue seem to be the reason kartograafr can't add users to the groups it creates in ArcGIS?

**Comment by ssciolla** [comment]
I believe it's related, but I haven't been focusing on investigating the issues with the currently running version of kartograafr in on-prem. I just know this is an issue we have now with the updated dependencies.
