### ISSUE TITLE
Assignment names with ":" and "/" character stopped cron job

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/kartograafr#50]
The ARCGIS group name uses format of "<CANVAS COURSE NAME>_<CANVAS COURSE ID>_<CANVAS ASSIGNMENT NAME>_<CANVAS ASSIGNMENT ID>"

The query string syntax for the ArcGIS REST API uses the colon as the separator between a key and its value. kartograafr is query the "title" key to check if there is already an existing group, e.g., 

```
2022-01-03 10:45:30,067 - arcgis._impl.connection - ERROR - You already have a group named 'KRSTD 392 001 WN 2022_506095_StoryMap Weekly Journal: Olle_1619491'. Try a different name.
2022-01-03 10:45:30,067 - arcgisUM - ERROR - Exception while creating ArcGIS group "KRSTD 392 001 WN 2022_506095_StoryMap Weekly Journal: Olle_1619491": Unable to create group.
You already have a group named 'KRSTD 392 001 WN 2022_506095_StoryMap Weekly Journal: Olle_1619491'. Try a different name.
(Error Code: 400)
Traceback (most recent call last):
  File "/kartograafr/arcgisUM.py", line 185, in createNewArcGISGroup
    group = arcGIS.groups.create(groupTitle,groupTags)
  File "/usr/local/lib/python3.7/site-packages/arcgis/gis/__init__.py", line 2808, in create
    group = self._portal.create_group_from_dict(params, thumbnail)
  File "/usr/local/lib/python3.7/site-packages/arcgis/_impl/portalpy.py", line 502, in create_group_from_dict
    resp = self.con.post('community/createGroup', postdata, files)
  File "/usr/local/lib/python3.7/site-packages/arcgis/_impl/connection.py", line 1183, in post
    self._handle_json_error(resp_json['error'], errorcode)
  File "/usr/local/lib/python3.7/site-packages/arcgis/_impl/connection.py", line 1204, in _handle_json_error
    raise RuntimeError(errormessage)
```

If the <ARCGIS GROUP NAME> value contains ":" character inside, that will cause group lookup based on only substring of <ARCGIS GROUP NAME> value

**Comment by jonespm** [comment]
There could be other characters that are reserved too. This one had a slash that resulted in a similar error

`2021-08-30 13:15:13,816 - arcgis._impl.connection - DEBUG - RESPONSE: https://umich.maps.arcgis.com/sharing/rest/community/createGroup, {"error":{"code":400,"messageCode":"COM_0044","message":"Unable to create group.","details":["You already have a group named 'URP 520 001 FA 2021_462070_ESRI Account/Software Survey_1415724'. Try a different name."]}}`

**Comment by ssciolla** [comment]
Yep, I recall that and one other case. There seems to be some special character handling already built in, but this could be an opportunity to improve more generally.

**Comment by zqian** [comment]
The current fix is to replace all occurrences of ':' and '/' with '-' inside course name and assignment name strings.

The fix does not differentiate ':' vs '/', so it will generate "group already exists" error, when handling assignment lists like

-  'one assignment with : inside' and 'one assignment with / inside', 
-  or  'one assignment with : and / inside' and 'one assignment with / and : inside'. 

But I think those are rare cases that we can ignore for now.

**Comment by zqian** [comment]
Discussed with Sam today on the proposed "filter" approach. Looks like the ArcGIS API Python package does not support the "filter" feature as of now. 

This simple update works: include the full string of group title inside double quotes,  e.g. f'title:"{title}"', instead of "title:"+title

Verified the fix works with the assignments with combinations of ':', '/', single quote and double quote inside the title string: e.g. 

- ArcGIS assignment with : in title " ' " ' / characters
- ArcGIS assignment with : in title " ' " ' / characters II
- ArcGIS assignment with : in title " ' / III
